spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=springapps;sslProtocol=TLS;trustServerCertificate=true
    username: sa
    password: password1
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: sql_server
    database-platform: org.hibernate.dialect.SQLServerDialect
